### ISSUE TITLE
看了下代码。好像不能使用到V5.0++ 新版本上

### ISSUE THREAD

**Issue by yaobo-lab** [xiangxud/transfer#1]
你好。你这分支能兼容的是 n9e 的那个版本？

**Comment by xiangxud** [comment]
是很早的版本v35，查询也没做连接池，后面没有怎么做了，不过大框架没什么问题，你可以自己根据tdengine的最新驱动和夜莺的驱动来改，这里主要是实现了根据指标名称动态建表，TDengine3.0性能更强大，可以关注

**Comment by yaobo-lab** [comment]
n9e 5.+ 版本的，能使用 TDengine 不？

**Comment by xiangxud** [comment]
从两个方面来看：

写：夜莺收到时序数据写到后端时序库，走的prometheus的remote write协议，TDEngine好像支持这个协议，所以，数据是可以写给TDEngine的
读，夜莺从时序库读取数据，走的是prometheus的querier接口，就是那些/api/v1/query /api/v1/series类的接口，没有这些接口就没法绘图。如果不支持这些接口，至少也要兼容支持 /api/v1/query接口，这样至少能配置报警
综上，不太清楚TDEngine现在支持这些prometheus协议的接口支持到了什么程度了，夜莺目前不会去适配其他时序库的接口协议

**Comment by yaobo-lab** [comment]
谢谢大老
